from __future__ import annotations

import argparse
import json

from .brokers.practice_orders import (
    submit_alpaca_paper_protected_order,
    submit_oanda_practice_market_order,
)
from .preflight import run_preflight


def _print_result(result) -> None:
    print(
        json.dumps(
            {
                "broker": result.broker,
                "ok": result.ok,
                "message": result.message,
                "details": result.details,
            },
            indent=2,
            sort_keys=True,
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Submit one explicitly confirmed broker-protected paper/practice test order"
    )
    parser.add_argument("--broker", required=True, choices=["alpaca", "oanda"])
    parser.add_argument("--symbol", required=True)
    parser.add_argument("--side", choices=["buy", "sell"], default="buy")
    parser.add_argument("--qty", type=float)
    parser.add_argument("--units", type=int, default=1)
    parser.add_argument(
        "--stop-price",
        type=float,
        required=True,
        help="Required broker-side protective stop price for the practice test",
    )
    parser.add_argument(
        "--client-order-id",
        help="Optional idempotency/client order identifier generated by the safety layer",
    )
    parser.add_argument("--ledger", default="var/autotrader/portfolio.db")
    parser.add_argument("--idempotency", default="var/autotrader/idempotency.db")
    parser.add_argument("--initial-equity", type=float, default=2000.0)
    parser.add_argument(
        "--confirm-practice-order",
        action="store_true",
        help="Required acknowledgement that this command submits a simulated broker order",
    )
    args = parser.parse_args()

    if not args.confirm_practice_order:
        parser.error("--confirm-practice-order is required")
    if args.stop_price <= 0:
        parser.error("--stop-price must be positive")

    preflight = run_preflight(
        ledger_path=args.ledger,
        idempotency_path=args.idempotency,
        initial_equity=args.initial_equity,
    )
    if not preflight.ready:
        parser.error(
            "practice-order submission blocked by preflight: "
            + ", ".join(preflight.failed_checks)
        )

    if args.broker == "alpaca":
        if args.qty is None or args.qty <= 0:
            parser.error("--qty must be positive for Alpaca protected orders")
        result = submit_alpaca_paper_protected_order(
            args.symbol,
            side=args.side,
            qty=args.qty,
            stop_price=args.stop_price,
            client_order_id=args.client_order_id,
        )
    else:
        units = abs(args.units) if args.side == "buy" else -abs(args.units)
        result = submit_oanda_practice_market_order(
            args.symbol,
            units=units,
            stop_price=args.stop_price,
            client_order_id=args.client_order_id,
        )
    _print_result(result)


if __name__ == "__main__":
    main()
